name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  frontend:
    name: Frontend build (Vite)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Typecheck & build
        run: npm run build

  rust:
    name: Rust build (Tauri backend)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Linux deps (Tauri)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            build-essential \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            libsoup2.4-dev \
            libglib2.0-dev \
            libjavascriptcoregtk-4.0-dev
      - name: Install Windows deps (NSIS & WiX)
        if: runner.os == 'Windows'
        run: choco install -y nsis wixtoolset
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2.8.1
        with:
          workspaces: |
            src-tauri
      - name: Cargo build (no bundle)
        run: cargo build --manifest-path src-tauri/Cargo.toml --locked
