name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build installers and create GitHub Release
  # No extra job condition needed: workflow only runs on tag pushes
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
          - os: windows-latest
            target: windows
          - os: macos-latest
            target: macos
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install Linux deps (Tauri)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            build-essential \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            libsoup2.4-dev \
            libglib2.0-dev \
            rpm
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src-tauri
      - name: Install Windows deps (NSIS & WiX)
        if: runner.os == 'Windows'
        run: |
          choco install -y nsis wixtoolset
      - name: Install JS deps
        run: npm ci
      - name: Build app bundles with Tauri
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        run: |
          npm run tauri build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-bundles-${{ matrix.target }}
          path: |
            src-tauri/target/release/bundle/**
      - name: Create release (draft)
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            src-tauri/target/release/bundle/**
