name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build installers
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: linux
          - os: windows-latest
            target: windows
          - os: macos-latest
            target: macos
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install Linux deps (Tauri)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            build-essential \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            libsoup2.4-dev \
            libglib2.0-dev \
            libjavascriptcoregtk-4.0-dev \
            rpm
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src-tauri
      - name: Install Windows deps (NSIS & WiX)
        if: runner.os == 'Windows'
        run: choco install -y nsis wixtoolset
      - name: Install JS deps
        run: npm ci
      - name: Build app bundles with Tauri
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        run: npm run tauri build
      - name: Zip macOS .app bundle
        if: runner.os == 'macOS'
        run: |
          set -e
          APP_DIR=$(ls -d src-tauri/target/release/bundle/macos/*.app 2>/dev/null | head -n 1 || true)
          if [ -n "$APP_DIR" ]; then
            ZIP_PATH="${APP_DIR}.zip"
            # Use ditto to preserve macOS bundle metadata
            ditto -c -k --sequesterRsrc --keepParent "$APP_DIR" "$ZIP_PATH"
            echo "Zipped $APP_DIR -> $ZIP_PATH"
          else
            echo "No .app bundle found to zip"
          fi
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-bundles-${{ matrix.target }}
          path: |
            src-tauri/target/release/bundle/**/*.exe
            src-tauri/target/release/bundle/**/*.msi
            src-tauri/target/release/bundle/**/*.deb
            src-tauri/target/release/bundle/**/*.rpm
            src-tauri/target/release/bundle/**/*.AppImage
            src-tauri/target/release/bundle/**/*.dmg
            src-tauri/target/release/bundle/**/*.app.zip

  release:
    name: Create GitHub Release (draft)
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: app-bundles-*
          path: release-assets
          merge-multiple: true
      - name: Generate SHA256 checksums
        run: |
          set -e
          shopt -s globstar nullglob
          pushd release-assets > /dev/null
          files=(**/*.exe **/*.msi **/*.deb **/*.rpm **/*.AppImage **/*.dmg **/*.app.zip)
          if [ ${#files[@]} -gt 0 ]; then
            sha256sum "${files[@]}" > ../SHA256SUMS.txt
            echo "Generated SHA256SUMS.txt for ${#files[@]} files"
          else
            echo "No matching files found for checksum generation" > ../SHA256SUMS.txt
          fi
          popd > /dev/null
      - name: Create draft release and attach assets
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            release-assets/**/*.exe
            release-assets/**/*.msi
            release-assets/**/*.deb
            release-assets/**/*.rpm
            release-assets/**/*.AppImage
            release-assets/**/*.dmg
            release-assets/**/*.app.zip
            SHA256SUMS.txt
